---
# ssh-2fa.yml

- name: CONFIGURE PAM AND SSHD FOR 2FA
  hosts: all
  vars:
    - packages:
        - google-authenticator
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
  tasks:
    - name: ENSURE DEPENDENCIES ARE PRESENT
      package:
        name: "{{ packages }}"

    - name: ENSURE PAM RULE EXISTS
      pamd:
        name: sshd
        new_type: auth
        new_control: required
        new_module_path: pam_google_authenticator.so
        module_arguments: nullok
        state: before
        type: auth
        control: include
        module_path: postlogin
        backup: yes
      notify: restart ssh

    - name: ENSURE SSHD IS CONFIGURED
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        backup: yes
      loop:
        -
          regexp: "^ChallengeResponseAuthentication .*"
          line: "ChallengeResponseAuthentication yes"
        -
          regexp: "^AuthenticationMethods .*"
          line: "AuthenticationMethods keyboard-interactive,publickey keyboard-interactive,password"
      notify: restart ssh
